base_url = "https://chaojie.fun"
title = "Chaojie's Home ✍️"
description = "The place where Chaojie writes"
default_language = "en"
compile_sass = true
build_search_index = false
generate_feed = true
theme = "willow"

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
render_emoji = true


[languages.en.translations]
language_name = "English"
home = "Home"
articles = "Articles"
tags = "Tags"
photography = "Photography"
about = "About"
memos = "Memos"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

[languages.zh-CN.translations]
language_name = "中文"
home = "首页"
articles = "文章"
tags = "标签"
photography = "摄影"
about = "关于"
memos = "碎碎念"
date_format = "%Y-%m-%d"
next_page = "下一页"
last_page = "上一页"

[extra]


[extra.willow]
# show_article_num = 2
nav = ["articles", "memos", "tags", "about"]
google_analytics = "G-XDREGKCZH0"

[extra.willow.social]
twitter = "chaojie_cn"
douban = "218724191"
github = "ischaojie"

[extra.willow.photography]
type = "unsplash"
unsplash_client_id = "Nzn8Fo0oteghIaTz-B0AAH3GQ-7BH2XNqWiJpE1AsB8"
unsplash_author = "chaojie"
photos = [
    "https://file.chaojie.fun/photography/过春天.jpg",
    "https://file.chaojie.fun/photography/lan.jpg",
    "https://file.chaojie.fun/photography/我和π.jpg",

]


[extra.willow.comment.giscus]
repo = "ischaojie/blog"
repo_id = "MDEwOlJlcG9zaXRvcnkyODk4MDA1NTY="
category = "Announcements"
category_id = "DIC_kwDOEUYBbM4CPWbs"
mapping = "title"

[extra.willow.memos]
show_num = 10
api = "https://momo.chaojie.fun/api/memo/all"
