name = "willow"
description = "A zola theme"
license = "MIT"
homepage = "https://github.com/ischaojie/willow"
# The minimum version of Zola required
min_version = "0.17.2"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

[extra.cacus]
google_analytics_enabled = true
google_analytics_id = ''
utterances_enabled = true
utterances_repo = ''
utterances_issue_term = 'pathname'
utterances_theme = 'github-light'
disqus_enabled = false

[author]
name = "chaojie"
homepage = "https://chaojie.fun"
