name: deploy to qiniu

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: download source file
        uses: actions/checkout@v2
        with:
            ref: master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      - name: Build
        run: hugo

      - name: deploy to qiniu
        env:
          QINIU_ACCESSKEY: ${{ secrets.QINIU_ACCESSKEY }}
          QINIU_SECRETKEY: ${{ secrets.QINIU_SECRETKEY }}
          SERVER_SCKEY: ${{ secrets.SERVER_SCKEY }}
        run: |
          chmod +x ./qshell
          ./qshell account $QINIU_ACCESSKEY $QINIU_SECRETKEY zhuzhezhe95@gmail.com
          ./qshell qupload2 --src-dir=./public --bucket=blog --overwrite=true
          wget https://sc.ftqq.com/$SERVER_SCKEY.send?text="blog部署OK"

